# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f25a505dd62de40dfc845fd4e1561ad855fec203d979512dafdf1f6fb0ea7bab092bdde56eea880475106b2b6318f533ea1013a6dae4952c9afeb0d260f4b9d4

test:
  secret_key_base: c448769e866fb91cb945e4c0eee7558dbb06ff3d8488c830a0281065b759fa97f3d7db60d6dd08fb8d25ffbf52e4fe9790bb9b3dc190c60b3c4f775c46f79fd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
